# Generated by Django 2.2 on 2019-04-27 01:31

from django.db import migrations
import photogallery.fields


class Migration(migrations.Migration):

    dependencies = [
        ('photogallery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=photogallery.fields.ThumbnailImageField(upload_to='photos'),
        ),
    ]
